
import "../../assets/fonts/pretendard/static/Pretendard-Thin.otf";
import "../../assets/fonts/pretendard/static/Pretendard-Light.otf";
import "../../assets/fonts/pretendard/static/Pretendard-ExtraLight.otf";
import "../../assets/fonts/pretendard/static/Pretendard-Regular.otf";
import "../../assets/fonts/pretendard/static/Pretendard-Medium.otf";
import "../../assets/fonts/pretendard/static/Pretendard-SemiBold.otf";
import "../../assets/fonts/pretendard/static/Pretendard-Bold.otf";

export global Fonts {
    out property <string> sans: "Pretendard";
}
