import { ListView, Button } from "std-widgets.slint";

import { Fonts } from "../common/fonts.slint";

export struct RecentProject {
    path: string,
    name: string,
}

export component LandingWindow inherits Window {
    in property <[RecentProject]> recent-projects;

    callback new-project();

    default-font-family: Fonts.sans;
    HorizontalLayout {
        padding: 16px;

        VerticalLayout {
            Image {
                source: @image-url("../../assets/images/logo/logo-light-theme.png");
                width: 320px;
                image-rendering: pixelated;
            }

            Text {
                text: "v0.0.1";

                vertical-stretch: 0;
            }

            Rectangle { }

            HorizontalLayout { }
        }

        VerticalLayout {
            HorizontalLayout {
                Text {
                    text: "Recent Projects";
                }

                Button {
                    text: "(+) New Project";

                    clicked => {
                        root.new-project();
                    }
                }
            }

            ListView { }
        }
    }
}
