import { ListView, Button } from "std-widgets.slint";

import { Fonts } from "../common/fonts.slint";

export struct RecentProject {
    path: string,
    name: string,
}

export component LandingWindow inherits Window {
    in property <[RecentProject]> recent-projects;

    callback new-project();

    default-font-family: Fonts.sans;
    HorizontalLayout {
        padding: 16px;

        VerticalLayout {
            Text {
                text: "@bitmap-font/";

                vertical-stretch: 0;

                font-size: 24px;
            }

            Text {
                text: "STUDIO";

                vertical-stretch: 0;

                font-weight: 900;
                font-size: 16px;
                letter-spacing: 4px;
            }

            Text {
                text: "v0.0.1";

                vertical-stretch: 0;
            }

            Rectangle { }

            HorizontalLayout { }
        }

        VerticalLayout {
            Text {
                text: "Recent Projects";
            }

            ListView { }

            Button {
                text: "(+) New Project";

                clicked => {
                    root.new-project();
                }
            }
        }
    }
}
